#!/usr/bin/perl -w
use lib qw(lib);
use strict;
use Device::Ericsson::AccessoryMenu;
use Device::SerialPort;

# before you start map Bluetooth-Serial with
# /Applications/Utilities/Bluetooth Serial Utility.app

my $port = shift || '/dev/cu.Bluetooth-Serial';

# XXX fill out Mac::Glue for iTunes stuff

my $remote = Device::Ericsson::AccessoryMenu->new(
    debug => 1,
    port  => Device::SerialPort->new( $port ) || die,
    menu  => [
        'Remote' => [
            Test => [
                "Send Text" => sub {
                    my $r = shift;
                    $r->send_text('hello, world', "isn't this fun");
                },
                "Dynamic Menu" => sub { [ Literal => 'What we have here is failure to communicate',] },
                Mouse  => sub {
                    my $r = shift;
                    $r->mouse_mode( callback => sub {
                                        my ($key, $updown) = @_;
                                        print "### key $key event $updown\n";
                                    });
                },
               ],
            Restart => sub { exec $^X, $0 },
            Quit    => sub { exit },
           ],
       ],
   );

$remote->register_menu;

print "Ready to rock.\n";

$remote->control while 1;
